src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Bio__c</fullName>
        <inlineHelpText>The BIO that will be displayed on Web Site.</inlineHelpText>
        <label>Bio</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Publish_on_Website__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When set to true the User details are published on the Web Site.</inlineHelpText>
        <label>Publish on Website?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <inlineHelpText>The ROLE that will be displayed on the Web Site.</inlineHelpText>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Business Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Junior Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Architect</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <label>User Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Employee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StellaxiusTeamComponentController.cls
public class StellaxiusTeamComponentController {
	public StellaxiusTeamComponentController() {
	}

	/**
		Get the List of Team Members that are published to the WebSite.

	*/
    public List<Employee__c> publishedTeamMembers {
		get {
			return [
				SELECT
					Id,
					Name,
					Role__c,
					Bio__c,
					User_Name__c
				FROM
					Employee__c
				WHERE
					Publish_On_Website__c = TRUE
				ORDER BY
					User_Name__c
			];
		}
    }

	/**
		The Site Prefix.

	*/
	public String siteBase {
		get {
			return StellaxiusSiteController.getSiteBase();
		}
	}

	/**

		Get the Site Prefix from current page URL.

	**/
	public static String getSiteBase() {
		return Site.getBaseUrl();
	}
}