src/objects/Employee__c.object
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Employee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Custom_Job_Title__c</fullName>
        <label>Custom Job Title</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Icon_Class__c</fullName>
        <label>Icon Class</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Job_Position__c</fullName>
        <inlineHelpText>Job Position will appear on the Web Site &quot;Join Us&quot; section and should be a short/clear description of the position for the job.</inlineHelpText>
        <label>Job Position</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Job_Specification__c</fullName>
        <inlineHelpText>Job Specification will appear on the Web Site when a link from a position in &quot;Join Us&quot; is clicked and a form is displayed showing the complete Job Specification.</inlineHelpText>
        <label>Job Specification</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <picklist>
            <picklistValues>
                <fullName>IT Project Manager / Business Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Architect / Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Junior Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Junior Business Analyst</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>JOB/{0000}</displayFormat>
        <label>Job Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Job_Title__c</fullName>
        <formula>IF(NOT(ISBLANK(Related_Job__r.Custom_Job_Title__c)), Related_Job__r.Custom_Job_Title__c,TEXT(Related_Job__r.Job_Title__c))</formula>
        <label>Job Title</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Site_Candidate_Lead__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeadSource__c</fullName>
        <label>LeadSource</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeadType__c</fullName>
        <label>LeadType</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MobilePhone__c</fullName>
        <label>MobilePhone</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Site Candidate Lead</label>
    <nameField>
        <displayFormat>CANDIDATE-LEAD-{0000}</displayFormat>
        <label>Site Candidate Lead Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Candidate Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Testimonial__c.object
<CustomObject>
    <label>Testimonial</label>
    <nameField>
        <label>Testemonial Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Testimonials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Website_Table__c.object
<CustomObject>
    <description>Tables for the Stellaxius Website.</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Description text that will appear linked with the Value field.</inlineHelpText>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Display_Order__c</fullName>
        <label>Display Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Icon_Class__c</fullName>
        <label>Icon Class</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table__c</fullName>
        <inlineHelpText>Name of the table where the pair (value, description) will appear.</inlineHelpText>
        <label>Table</label>
        <picklist>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Values</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <inlineHelpText>Value that identifies the description.</inlineHelpText>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Website Table</label>
    <nameField>
        <displayFormat>TD-{00000000}</displayFormat>
        <label>Website Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Website Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TEST_StellaxiusSite.cls
@isTest
global class TEST_StellaxiusSite {
	@isTest static void testSiteController() {
		setupReferenceData();

		StellaxiusSiteController controller = new StellaxiusSiteController();

		List<Website_Table__c> tableList = StellaxiusSiteController.getTableRecords('any');
		Map<String,Website_Table__c> tableMap = StellaxiusSiteController.getContactMap();
		List<Job__c> jobList = StellaxiusSiteController.getJobRecords();
		String str = controller.ourMissionJSON;
		Job__c job = StellaxiusSiteController.getJobByReference('JOB/000X');

		tableList = controller.ourMission;
		tableList = controller.ourValues;

		str = controller.ourValuesJSON;
		tableList = controller.services;
		str = controller.contactHeader;
		str = controller.contactEmail;
		str = controller.contactPhone;
		str = controller.contactAddress;
		str = controller.contactMap;
		jobList = controller.jobs;

		str = StellaxiusSiteController.getJobByReferenceJSON('JOB/000X');
	}

	@isTest static void testTeamComponentController() {
		setupReferenceData();

		StellaxiusTeamComponentController controller = new StellaxiusTeamComponentController();

		List<Employee__c> employeeList = controller.publishedTeamMembers;
	}

	@isTest static void testTestimonialComponentController() {
		setupReferenceData();

		StellaxiusTestimonialComponentController controller = new StellaxiusTestimonialComponentController();

		List<Testimonial__c> testimonialList = controller.publishedTestimonials;
	}

	@isTest static void testWebCandidateApplController() {
		setupReferenceData();

		StellaxiusWebCandidateApplController controller = new StellaxiusWebCandidateApplController();

		String str = controller.firstName;
		str = controller.lastName;
		str = controller.email;
		str = controller.mobilePhone;
		Attachment attachment = controller.leadAttachment;
		Job__c job = controller.job;
		str = controller.jobJSON;
		str = controller.retURL;
		PageReference pageReference = controller.upload();
	}

	@isTest static void testImportSiteCandidatesBatch() {
		setupReferenceData();

		ImportSiteCandidatesBatch zbatch = new ImportSiteCandidatesBatch();

		Site_Candidate_Lead__c candidateLead = new Site_Candidate_Lead__c(
			FirstName__c = 'First',
			LastName__c = 'Last',
			Email__c = 'abc@def.com',
			MobilePhone__c = '+351210000001',
			LeadSource__c = 'Website',
			LeadType__c = 'Candidate Application',
			Company__c = 'Stellaxius RH'
		);

		insert candidateLead;

		ImportSiteCandidatesBatch.runOnce();

		//ImportSiteCandidatesBatch.defaultSchedule();

		Lead zlead = zbatch.getLead(candidateLead);

		insert zlead;

		ImportSiteCandidatesBatch.sendTemplateEmail(
			new String[] { 'a.santos@gmail.com' },
			new String[] { },
			'Job_Submission_Received',
			zlead.Id,
			null,
			null
		);

		zbatch.execute(null, new List<Site_Candidate_Lead__c> { candidateLead });
	}

	private static void setupReferenceData() {
		List<Website_Table__c> tableList = new List<Website_Table__c>();
		List<Employee__c> employeeList = new List<Employee__c>();
		List<Job__c> jobList = new List<Job__c>();

		tableList.add(
			new Website_Table__c(
				Table__c = 'Services',
				Display_Order__c = 1,
				Value__c = 'Test',
				Description__c = 'Test',
				Icon_Class__c = 'xpto'
			)
		);

		tableList.add(
			new Website_Table__c(
				Table__c = 'Values',
				Display_Order__c = 1,
				Value__c = 'Test',
				Description__c = 'Test',
				Icon_Class__c = 'xpto'
			)
		);

		tableList.add(
			new Website_Table__c(
				Table__c = 'Mission',
				Display_Order__c = 1,
				Value__c = 'Test',
				Description__c = 'Test',
				Icon_Class__c = 'xpto'
			)
		);

		tableList.add(
			new Website_Table__c(
				Table__c = 'Contact',
				Display_Order__c = 1,
				Value__c = 'header',
				Description__c = 'Test',
				Icon_Class__c = 'xpto'
			)
		);

		tableList.add(
			new Website_Table__c(
				Table__c = 'Contact',
				Display_Order__c = 2,
				Value__c = 'email',
				Description__c = 'Test',
				Icon_Class__c = 'xpto'
			)
		);

		tableList.add(
			new Website_Table__c(
				Table__c = 'Contact',
				Display_Order__c = 3,
				Value__c = 'phone',
				Description__c = 'Test',
				Icon_Class__c = 'xpto'
			)
		);

		tableList.add(
			new Website_Table__c(
				Table__c = 'Contact',
				Display_Order__c = 4,
				Value__c = 'address',
				Description__c = 'Test',
				Icon_Class__c = 'xpto'
			)
		);

		tableList.add(
			new Website_Table__c(
				Table__c = 'Contact',
				Display_Order__c = 5,
				Value__c = 'map',
				Description__c = 'Test',
				Icon_Class__c = 'xpto'
			)
		);

		insert tableList;

		/*
		employeeList.add(
			new Employee__c (
				
			)
		);

		insert employeeList;
		*/

		jobList.add(
			new Job__c(
				Job_Title__c = 'General Application',
				Icon_Class__c = 'xpto',
				Sort_Order__c = 1,
				Is_Active__c = true,
				Job_Position__c = 'Sample Job Position',
				Job_Specification__c = 'Sample Job Specification'
			)
		);

		jobList.add(
			new Job__c(
				Custom_Job_Title__c = 'Sample Custom Job Title',
				Icon_Class__c = 'xpto',
				Sort_Order__c = 1,
				Is_Active__c = true,
				Job_Position__c = 'Sample Job Position',
				Job_Specification__c = 'Sample Job Specification'
			)
		);

		insert jobList;

	}
}