src/objects/Testimonial__c.object
<CustomObject>
    <fields>
        <fullName>Photo_Resource__c</fullName>
        <label>Photo Resource</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publish_on_Website__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Publish on Website?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Testimonial_Text__c</fullName>
        <label>Testimonial Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Testimonial</label>
    <nameField>
        <label>Testemonial Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Testimonials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StellaxiusTestimonialComponentController.cls
public with sharing class StellaxiusTestimonialComponentController {
    public StellaxiusTestimonialComponentController() { 
    }

    /**
        Get the List of Testimonials that are published to the WebSite.

    */
    public List<Testimonial__c> publishedTestimonials {
        get {
            return [
                SELECT
                    Id,
                    Name,
                    Role__c,
                    Testimonial_Text__c,
                    Photo_Resource__c
                FROM
                    Testimonial__c
                WHERE
                    Publish_On_Website__c = TRUE
                ORDER BY
                    Name
            ];
        }
    }

    /**
        The Site Prefix.

    */
    public String siteBase {
        get {
            return StellaxiusSiteController.getSiteBase();
        }
    }

    /**

        Get the Site Prefix from current page URL.

    **/
    public static String getSiteBase() {
        return Site.getBaseUrl();
    }
}